#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
echo $BUCKET_NAME
OBJECTS=$(aws s3api list-objects --bucket $BUCKET_NAME --query 'Contents[].{Key:Key}' --output json)
echo $OBJECTS|jq '.'
echo '{"Objects":' >delete.json
echo $OBJECTS|jq '.' >>delete.json
echo '}' >>delete.json

aws s3api delete-objects \
--bucket $BUCKET_NAME \
--delete file://delete.json
