#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check for object name
if [ -z "$2" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
OBJECT_KEY=$(basename $2)
FILE_BODY=$2

aws s3api put-object \
--bucket $BUCKET_NAME \
--key $OBJECT_KEY \
--body $FILE_BODY

